### ISSUE TITLE
Issue with twisted plugins

### ISSUE THREAD

**Issue by cedricpim** [mineo/sagbescheid#2]
I was trying to run sagbescheid by cloning the repo but I am getting a problem related to twisted. Here is the stacktrace:

```
Unexpected error while writing cache file
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sagbescheid-0.3.1.dev13+gd5016af-py3.5.egg/sagbescheid/__main__.py", line 6, in <module>

  File "/usr/local/lib/python3.5/dist-packages/sagbescheid-0.3.1.dev13+gd5016af-py3.5.egg/sagbescheid/sagbescheid.py", line 142, in main

  File "/usr/local/lib/python3.5/dist-packages/sagbescheid-0.3.1.dev13+gd5016af-py3.5.egg/sagbescheid/sagbescheid.py", line 101, in build_arg_parser

  File "/usr/local/lib/python3.5/dist-packages/Twisted-18.7.0-py3.5-linux-x86_64.egg/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/Twisted-18.7.0-py3.5-linux-x86_64.egg/twisted/plugin.py", line 185, in getCache
    dropinPath.setContent(pickle.dumps(dropinDotCache))
builtins.AttributeError: 'ZipPath' object has no attribute 'setContent'
```

Happens with both python2 and 3. Any ideas what it could be?

**Comment by cedricpim** [comment]
Actually, seems more related to python3. Feel free to close it if you are not thinking of porting it to python3.

**Comment by mineo** [comment]
I have only tested sagbescheid on Python 2 (it'll probably work on Python 3 with some `six` magic, but I don't know if it works right now), so let's focus on that.

Unfortunately I have never seen this before (Twisted 18.7.0 on Python 2.7.13 on Arch Linux & Raspbian). Googling that error message ends with very few results:

- https://tahoe-lafs.org/pipermail/tahoe-dev/2014-May/009031.html
- https://github.com/gleicon/restmq/issues/13
- https://twistedmatrix.com/trac/ticket/3985

none of which contain a fix for the problem :( The Twisted ticket mentions `sys.path` possibly playing a role here. Does it contain anything interesting, possibly elements that the `sys.path` of your systems python does not list?

**Comment by mineo** [comment]
Oh, that's good to know. So it actually works on Python 2?

I'm definitely open to moving to Python 3 at some point, but it's not a priority at the moment.
